[package]
name = "resnet"
version = "0.0.0"
authors = ["Ehsan M.Kermani <ehsanmo1367@gmail.com>"]
license = "Apache-2.0"
build = "build.rs"

[dependencies]
ndarray = "0.12.1"
tvm-frontend = { path = "../../" }
image = "0.20.1"
csv = "1"