[package]
name = "tvm-sys"
version = "0.1.0"
authors = ["Ehsan M.Kermani <ehsanmo1367@gmail.com>"]
license = "Apache-2.0"
description = "TVM runtime bindings"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.37.0"

[features]
# for dev usage only
nightly = []